name: Android Emulator Tests

on:
  push:
    branches:
      - ci/setup-slack-alerts

env:
  DOTENV_CONFIG_QUIET: true
  STANDARD_USER: ${{ secrets.STANDARD_USER }}
  STANDARD_PASSWORD: ${{ secrets.STANDARD_PASSWORD }}
  LOCKED_OUT_USER: ${{ secrets.LOCKED_OUT_USER }}
  LOCKED_OUT_PASSWORD: ${{ secrets.LOCKED_OUT_PASSWORD }}

jobs:
  android-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      # Send a notification ONLY if the pipeline fails
      - name: Notify Slack on Failure
        if: failure()
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "❌ *CI/CD Build Failed!*",
              "attachments": [
                {
                  "color": "#danger",
                  "text": "Repo: ${{ github.repository }}\nCommit: ${{ github.sha }}\nAuthor: ${{ github.actor }}"
                }
              ]
            }

      # Send a notification ONLY if the pipeline succeeds
      - name: Notify Slack on Success
        if: success()
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "🚀 *CI/CD Build Succeeded!*",
              "attachments": [
                {
                  "color": "#good",
                  "text": "The changes have successfully passed all pipeline checks."
                }
              ]
            }
