name: Appium WDIO Test

on:
  push:
    branches:
      - ci/android-test-workflow
  pull_request:
    branches:
      - ci/android-test-workflow

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  DOTENV_CONFIG_QUIET: true

jobs:
  mobile-test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: |
          npm ci

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          profile: pixel_5
          emulator-boot-timeout: 900
          disable-animations: true
          script: |
            adb devices

      - name: Verify Emulator
        run: |
          adb devices
